### ISSUE TITLE
Data packet question

### ISSUE THREAD

**Issue by meachware** [system123/ios_simulator_sensors#2]
Will the CMManagerSim work without using a queue?

Example code:
- (void)startAccelerometerUpdatesToQueue:(NSOperationQueue *)queue withHandler:(CMAccelerometerHandler)handler {

I don't use that in my game <- so is that why I'm struggling to 'get' data from my iPhone in the simulator?

Sorry, I realize it's not a "real" issue, just thought it would be a good way to contact you.
Thanks!

**Comment by system123** [comment]
You need to use a queue as it is threaded code. So no it won't work if you don't use a queue. You can always extend the library if you need. Just make a buffer to save the last received data and then query that instead. That is a polling approach, the way the library works is with callbacks.
